DEFAULT_REGION = "ap-northeast-2"
DEFAULT_ROLE_NAME = "spaceoneRole"
ADMIN_POLICY_ARN = "arn:aws:iam::aws:policy/ReadOnlyAccess"
CONTROL_TOWER_ROLE_NAME = "AWSControlTowerExecution"
SECURITY_OU_NAME = "Security"
